gitlab-redis:
  image: index.docker.io/sameersbn/redis:4.0.9
  command: --protected-mode no
  restart: always
  volumes:
  - /mnt/diskb/docker/gitlab/redis:/var/lib/redis
gitlab-mysql:
  image: index.docker.io/sameersbn/mysql:latest
  restart: always
  ports:
  - 32777:3306
  volumes:
  - /mnt/diskb/docker/gitlab/mysql:/var/lib/mysql
  environment:
  - DB_USER=gitlab
  - DB_PASS=gitlabpaw
  - DB_NAME=gitlabhq_production
gitlab:
  image: index.docker.io/sameersbn/gitlab:9.3.5
  restart: always
  links:
  - gitlab-redis:redisio
  - gitlab-mysql:mysql
  ports:
  - 10081:80
  - '10023:22'
  volumes:
  - /mnt/diskb/docker/gitlab/gitlab:/home/git/data
  environment:
  - GITLAB_SECRETS_DB_KEY_BASE=Eatievomog3ucahjaivahfaigeiphahc
  - GITLAB_SECRETS_SECRET_KEY_BASE=Eatievomog3ucahjaivahfaigeiphahc
  - GITLAB_SECRETS_OTP_KEY_BASE=Eatievomog3ucahjaivahfaigeiphahc
  - GITLAB_SSH_PORT=10023
  - GITLAB_PORT=80
  - SMTP_HOST=smtp.exmail.qq.com
  - SSL_SELF_SIGNED=true
  - TZ=Asia/Shanghai
  - GITLAB_HOST=git.inner.shengyisoft.com
  - GITLAB_HTTPS=false
  - SMTP_PORT=465
  - SMTP_USER=admin@shengyisoft.com
  - GITLAB_BACKUP_SCHEDULE=daily
  - SMTP_TLS=true
  - SMTP_STARTTLS=true
  - GITLAB_EMAIL_REPLY_TO=admin@shengyisoft.com
  - SMTP_AUTHENTICATION=login
  - GITLAB_GRAVATAR_ENABLED=true
  - NGINX_MAX_UPLOAD_SIZE=100m
  - GITLAB_TIMEZONE=Beijing
  - DEBUG=
  - GITLAB_EMAIL=admin@shengyisoft.com
  - SMTP_DOMAIN=smtp.exmail.qq.com
  - GITLAB_BACKUP_TIME=03:00
  - SMTP_ENABLED=true
  - GITLAB_GRAVATAR_HTTP_URL=http://gravatar.duoshuo.com/avatar/%{hash}?s=%{size}&d=identicon
  - GITLAB_EMAIL_DISPLAY_NAME=gitlab
  - SMTP_PASS=9pFQDGmw
